# Generated by Django 4.2.10 on 2024-02-26 17:09

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('featured_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='articles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='categories')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='subcategories', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Tag')),
                ('language',
                 models.CharField(choices=[('en', 'English'), ('hy', 'Հայերեն'), ('ru', 'Русский')], default='en',
                                  max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language',
                 models.CharField(choices=[('en', 'English'), ('hy', 'Հայերեն'), ('ru', 'Русский')], default='en',
                                  max_length=4)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True,
                                            help_text='Language specific image. If not set category default image will be taken.',
                                            null=True, upload_to='categories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content',
                                               to='blog.category')),
            ],
            options={
                'verbose_name': 'Category Content',
                'verbose_name_plural': 'Categories Contents',
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language',
                 models.CharField(choices=[('en', 'English'), ('hy', 'Հայերեն'), ('ru', 'Русский')], default='en',
                                  max_length=4)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_contents')),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content',
                                              to='blog.article')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles_contents', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Articles Contents',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.category',
                                         verbose_name='Related Categories'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_articles',
                                    to='blog.category', verbose_name='Main Category'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('slug',), name='article_slug_unique'),
        ),
    ]
