# Generated by Django 4.2.10 on 2024-02-26 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlecontent',
            unique_together={('article', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='categorycontent',
            unique_together={('category', 'language')},
        ),
    ]
