# Generated by Django 4.2.20 on 2025-03-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_publisher'),
        ('blog', '0002_alter_articlecontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.publisher'),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('hy', 'Հայերեն'), ('en', 'English')], default='ru',
                                   max_length=4),
        ),
        migrations.AlterField(
            model_name='categorycontent',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('hy', 'Հայերեն'), ('en', 'English')], default='ru',
                                   max_length=4),
        ),
        migrations.AlterField(
            model_name='tag',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('hy', 'Հայերեն'), ('en', 'English')], default='ru',
                                   max_length=4),
        ),
    ]
