# Generated by Django 4.2.20 on 2025-03-08 06:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_alter_article_author_alter_articlecontent_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
