name: Deploy NewsPaper Prod

on:
  tags:
    - *

defaults:
  run:
    working-directory: /sites/newspaper

jobs:
  build-linux:
    runs-on: betta
    strategy:
      max-parallel: 5

    steps:
    - name: Update code
      run: |
        git pull origin main
    - name: Remove old env
      run: |
        rm -rf venv
    - name: Create new one
      run: |
        /usr/bin/python3.8 -m venv venv
    - name: Install wheel first
      run: |
        venv/bin/python -m pip install wheel
    - name: Install dependencies
      run: |
        venv/bin/python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        venv/bin/python manage.py test
        
    - name: Restart server
      run: |
        sudo systemctl restart newspaper.uwsgi.service
        sudo service nginx restart
