name: Deploy NewsPaper Prod

on: [push]

jobs:
  build-linux:
    runs-on: betta
    strategy:
      max-parallel: 5

    steps:
    - name: Remove old env
      run: |
        rm -rf /sites/newspaper/venv
    - name: Create new one
      run: |
        /usr/bin/python3.8 -m venv /sites/newspaper/venv
    - name: Install dependencies
      run: |
        pwd
        /sites/newspaper/venv/bin/python -m pip -r install requirements.txt
    - name: Run Tests
      run: |
        /sites/newspaper/venv/bin/python manage.py test
        
    - name: Restart server
      run: |
        sudo systemctl restart newspaper.uwsgi.service
        sudo service nginx restart
